# Generated by Django 4.2.3 on 2023-07-11 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seats.user'),
        ),
    ]
