# Generated by Django 4.2.3 on 2023-07-11 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0004_alter_allocation_owner_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='name',
        ),
    ]
